parameters:

services:

    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../Company/src/Entity/'
            - '../Employee/src/Entity/'
            - '../src/Kernel.php'
    _instanceof:
        App\Shared\Service\CQRS\Command\CommandHandler:
            tags:
                - { name: messenger.message_handler, bus: command.bus }
        App\Shared\Service\CQRS\Query\QueryHandler:
            tags:
                - { name: messenger.message_handler, bus: query.bus }
